### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Sumo99**
added footer, please note that the spacing is different, because my editor changed it. Let me know about any stylistic changes you need.

### CODE REVIEW

**Comment by rishabhKalakoti** [comment]
@Sumo99 Please deploy this branch at GitHub Pages so that it's easy for me to review.
And now remove the conflicts too.

**Comment by Sumo99** [comment]
Ok I have resolved the conflict, sorry for the delay.

**Comment by rishabhKalakoti** [comment]
Please also Deploy the branch you want to merge on Github pages, it makes it easier to review

**Comment by rishabhKalakoti** [comment]
The footer doesn't look great like this.
It would be better to have it in the sidebar i guess.
#15 is looking into it. 
You can take #5 if you want to.

**Comment by rishabhKalakoti** [comment]
Btw, you don't put copyright unless you have registered one. XD

**Comment by Sumo99** [comment]
I know, I did not know know if you need copy left or creative commons or what, so I went with copyright

**Comment by rishabhKalakoti** [comment]
I will close this one for now. Make another PR if you work on something.

**Pull request closed without merging**
