### PR TITLE
Box-Borders on Team page modified

### PR DESCRIPTION
**Pull request by dhruvgolani**
Changed the border color and shadows to make UI of team page better.

### CODE REVIEW

**Comment by rishabhKalakoti** [comment]
@dhruvgolani  Deploy your copy of the repo in Github pages so that i can review easily

**Comment by rishabhKalakoti** [comment]
Yours is a small change in frontend. Make more useful PR's. Maybe take up #1 and commit on the same PR

**Comment by dhruvgolani** [comment]
Ok I will do it.

**Comment by rishabhKalakoti** [comment]
The preloader css, move it to another css file to for more simplicity. something like `preloader.css`

**Comment by rishabhKalakoti** [comment]
And i also asked you to deploy the website on github pages. It's easier to review that way

**Pull request merged**
