### PR TITLE
Fix for Issue #5

### PR DESCRIPTION
**Pull request by Sumo99**
I fixed Issue #5 by removing the stuff from the tutorials page and creating a pdf and embedding it inside the tutorials dropdown. Screenshots attached. I also added quotes to the loading screen.

2019-04-17-150432_1920x1080_scrot
2019-04-17-150507_1920x1080_scrot

### CODE REVIEW

**Comment by rishabhKalakoti** [comment]
1. Please deploy the repository at Github Pages instead of adding screenshots.
https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages
2. Just give links to pdfs. Don't load them here itself.

**Comment by Sumo99** [comment]
1. 
You can see the deployment here https://sumo99.github.io/codeshows.github.io/#

2. I have given the links to the pdfs, on second inspection it is better to give the links than the embed so that the user can control whether they want to click on the pdfs.

**Comment by rishabhKalakoti** [comment]
Please add tutorial 4 and 5 too. In 4 you can simply write the content and give the link that was provided. And move the pdf's to a folder named tutorials. Show the recent ones on top (descending order). That would be all I guess.

**Comment by Sumo99** [comment]
Where is tutorial 5?

**Comment by rishabhKalakoti** [comment]
Find tutorials at facebook.com/codeshows. You will have to join the group. I think it was a private post.
Otherwise this is the link to the drive. You will have to convert it to pdf.
https://docs.google.com/document/d/1eljEXxEzB4FWysb3iKDqTp9JJg2Mmhp0WPtXBwDUlr8/edit

**Comment by rishabhKalakoti** [comment]
Good Job!

**Pull request merged**
